config/routes.rb
Rails.application.routes.draw do
  root "users#feed"

  devise_for :users
  
  resources :comments
  resources :follow_requests
  resources :likes
  resources :photos

  get ":username" => "users#show", as: :user
  get ":username/liked" => "users#liked", as: :liked
  get ":username/feed" => "users#feed", as: :feed
  get ":username/discover" => "users#discover", as: :discover
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :bigint           not null
#  photo_id   :bigint           not null
#
# Indexes
#
#  index_comments_on_author_id  (author_id)
#  index_comments_on_photo_id   (photo_id)
#
# Foreign Keys
#
#  fk_rails_...  (author_id => users.id)
#  fk_rails_...  (photo_id => photos.id)
#
class Comment < ApplicationRecord
  belongs_to :author, class_name: "User", counter_cache: true
  belongs_to :photo, counter_cache: true

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  before_action :ensure_current_user_is_owner, only: [:destroy, :update, :edit]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_back fallback_location: root_path, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to root_url, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def ensure_current_user_is_owner
      if current_user != @comment.author
        redirect_back fallback_location: root_url, alert: "You're not authorized for that."
      end
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:author_id, :photo_id, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li class="list-group-item">
  <div class="media">
    <%= image_tag comment.author.avatar_image, class: "rounded-circle mr-2", width: 36 %>
    <div class="media-body">
      <div class="d-flex align-items-center justify-content-between">
        <h5 class="mt-0">
          <%= link_to comment.author.username, user_path(comment.author.username), class: "text-dark" %>
        </h5>

        <div>
          <% if current_user == comment.author %>
            <%= link_to edit_comment_path(comment), class: "btn btn-link btn-sm text-muted" do %>
              <i class="fas fa-edit fa-fw"></i>
            <% end %>

            <%= link_to comment, method: :delete, class: "btn btn-link btn-sm text-muted" do %>
              <i class="fas fa-trash fa-fw"></i>
            <% end %>
          <% end %>
        </div>
      </div>
      <p><%= comment.body %></p>
    </div>
  </div> 
</li>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <ul class="list-unstyled">
        <% comment.errors.each do |error| %>
          <li>
            <div class="alert alert-danger" role="alert">
              <%= error.full_message %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :photo_id %>

  <div class="form-group">
    <%= form.label :body, class: "sr-only" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-secondary btn-block" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="row mb-4">
  <div class="col-md-6 offset-md-3">
    <h1 class="display-4">editing comment</h1>
    
    <%= render 'form', comment: @comment %>
  </div>
</div>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Photo</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author_id %></td>
        <td><%= comment.photo_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author_id %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @comment.photo_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>